export global Palette {
    out property <color> bg:           #1e1e1e;
    // out property <color> sidebar-bg:   #242424;
    out property <color> sidebar-bg:   #000000;
    out property <color> surface:      #303030;
    out property <color> surface-hi:   #404040;
    out property <color> surface-lo:   #181818;

    out property <color> border:       #3a3a3a;
    out property <color> border-hi:    #4a4a4a;

    out property <color> accent:       #3584e4;
    out property <color> accent-hi:    #5b9deb;
    out property <color> accent-dim:   #3584e426;
    out property <color> accent-muted: #3584e44d;

    out property <color> danger:       #c01c28;
    out property <color> danger-hi:    #e01b24;
    out property <color> success:      #26a269;
    out property <color> success-hi:   #2ec27e;
    out property <color> warning:      #e5a50a;
    out property <color> warning-hi:   #f6d32d;
    out property <color> warning-bg:   #e5a50a18;

    out property <color> text:         #ffffff;
    out property <color> text-dim:     #9a9996;
    out property <color> text-dimmer:  #77767b;
    out property <color> text-accent:  #78aeed;
}
